export const PRODUCTS = [
  {
    name: "Lavarropas carga frontal 8kg",
    category: "lavado",
    price: 620000,
    installments: "6 cuotas sin interés",
    inStock: true,
    description: "1200 rpm de centrifugado, 12 programas de lavado.",
    specs: [
      { label: "Capacidad", value: "8 kg" },
      { label: "Centrifugado", value: "1200 rpm" },
      { label: "Programas de lavado", value: "12" },
      { label: "Carga", value: "Frontal" },
    ],
  },
  {
    name: "Anafe a gas 4 hornallas",
    category: "cocina",
    price: 210000,
    installments: "3 cuotas sin interés",
    inStock: true,
    description: "Parrillas de hierro fundido y encendido eléctrico integrado.",
    specs: [
      { label: "Hornallas", value: "4" },
      { label: "Encendido", value: "Eléctrico" },
      { label: "Material de parrillas", value: "Hierro fundido" },
    ],
  },
  {
    name: "Aire acondicionado split 3000W",
    category: "climatizacion",
    price: 780000,
    installments: "9 cuotas sin interés",
    inStock: false,
    description: "Frío/calor, tecnología inverter, incluye instalación básica.",
    specs: [
      { label: "Potencia", value: "3000W (frío/calor)" },
      { label: "Tecnología", value: "Inverter" },
      { label: "Instalación", value: "Incluida" },
    ],
  },
  {
    name: "Microondas 25L digital",
    category: "cocina",
    price: 180000,
    installments: "3 cuotas sin interés",
    inStock: true,
    description: "10 niveles de potencia, grill y programas automáticos.",
    specs: [
      { label: "Capacidad", value: "25 litros" },
      { label: "Niveles de potencia", value: "10" },
      { label: "Funciones", value: "Grill y programas automáticos" },
    ],
  },
  {
    name: "Licuadora 3 velocidades",
    category: "pequenos",
    price: 65000,
    installments: null,
    inStock: true,
    description: "Vaso de vidrio 1.5L, cuchillas de acero inoxidable.",
    specs: [
      { label: "Velocidades", value: "3" },
      { label: "Vaso", value: "Vidrio 1.5L" },
      { label: "Cuchillas", value: "Acero inoxidable" },
    ],
  },
];
