export const PRODUCTS = [
  {
    name: "Heladera No Frost 320L",
    category: "frio",
    price: 950000,
    installments: "12 cuotas sin interés",
    inStock: true,
    description: "Freezer superior, control de temperatura digital y bajo consumo.",
  },
  {
    name: "Lavarropas carga frontal 8kg",
    category: "lavado",
    price: 620000,
    installments: "6 cuotas sin interés",
    inStock: true,
    description: "1200 rpm de centrifugado, 12 programas de lavado.",
  },
  {
    name: "Anafe a gas 4 hornallas",
    category: "cocina",
    price: 210000,
    installments: "3 cuotas sin interés",
    inStock: true,
    description: "Parrillas de hierro fundido y encendido eléctrico integrado.",
  },
  {
    name: "Aire acondicionado split 3000W",
    category: "climatizacion",
    price: 780000,
    installments: "9 cuotas sin interés",
    inStock: false,
    description: "Frío/calor, tecnología inverter, incluye instalación básica.",
  },
  {
    name: "Microondas 25L digital",
    category: "cocina",
    price: 180000,
    installments: "3 cuotas sin interés",
    inStock: true,
    description: "10 niveles de potencia, grill y programas automáticos.",
  },
  {
    name: "Licuadora 3 velocidades",
    category: "pequenos",
    price: 65000,
    installments: null,
    inStock: true,
    description: "Vaso de vidrio 1.5L, cuchillas de acero inoxidable.",
  },
];
